import React, { useState } from "react";
import { ScanResult, Severity } from "../types";
import { ScoreGauge } from "./ScoreGauge";
import { 
  AlertOctagon, 
  CheckCircle2, 
  Globe, 
  ShieldAlert, 
  RotateCcw, 
  Copy, 
  Check, 
  Download, 
  ExternalLink,
  ChevronRight,
  HelpCircle,
  FileCheck,
  Building2,
  Lock,
  Cpu
} from "lucide-react";

interface ResultsDashboardProps {
  result: ScanResult;
  onReset: () => void;
}

export const ResultsDashboard: React.FC<ResultsDashboardProps> = ({
  result,
  onReset,
}) => {
  const [copied, setCopied] = useState(false);

  const getSeverityBadge = (sev: Severity) => {
    switch (sev) {
      case "critical":
        return "bg-rose-950/80 text-rose-300 border-rose-800/80";
      case "high":
        return "bg-orange-950/80 text-orange-300 border-orange-800/80";
      case "medium":
        return "bg-amber-950/80 text-amber-300 border-amber-800/80";
      case "low":
        return "bg-slate-800 text-slate-300 border-slate-700";
    }
  };

  const handleCopyReport = () => {
    const textReport = `==============================
SCAMSHIELD SECURITY AUDIT REPORT
==============================
Target: ${result.inputSnippet}
Threat Index: ${result.score}% (${result.riskLevel})
Timestamp: ${new Date(result.timestamp).toLocaleString()}
Engine: ${result.engine}

EXECUTIVE SUMMARY:
${result.summary}

RED FLAGS IDENTIFIED (${result.redFlags.length}):
${result.redFlags.map((rf, i) => `${i + 1}. [${rf.severity.toUpperCase()}] ${rf.title}\n   Evidence: "${rf.evidence}"\n   Explanation: ${rf.explanation}`).join("\n")}

POSITIVE SIGNALS (${result.positiveSignals.length}):
${result.positiveSignals.map((ps, i) => `${i + 1}. ${ps.title}: ${ps.explanation}`).join("\n")}

SAFETY RECOMMENDATIONS:
${result.recommendations.map((rec, i) => `- ${rec}`).join("\n")}

==============================
Generated by ScamShield v1.0
==============================`;

    navigator.clipboard.writeText(textReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `scamshield-report-${result.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div id="results-dashboard" className="w-full space-y-6">
      {/* Top Banner with Action Buttons */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 bg-slate-900/90 border border-slate-800 rounded-2xl">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-mono uppercase text-cyan-400 font-semibold tracking-wider">
              INSPECTION REPORT
            </span>
            <span className="text-slate-600">&bull;</span>
            <span className="text-xs text-slate-400 font-mono">
              ID: {result.id}
            </span>
          </div>
          <p className="text-sm text-slate-300 font-medium mt-0.5 truncate max-w-xl">
            Target: <span className="text-slate-400 italic font-mono text-xs">{result.inputSnippet}</span>
          </p>
        </div>

        <div className="flex items-center gap-2 self-end sm:self-auto">
          <button
            onClick={handleCopyReport}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? "Copied" : "Copy Report"}</span>
          </button>

          <button
            onClick={handleDownloadJson}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export JSON</span>
          </button>

          <button
            onClick={onReset}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-bold bg-cyan-500 hover:bg-cyan-400 text-slate-950 transition-colors"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>Scan Another</span>
          </button>
        </div>
      </div>

      {/* Hero Overview Grid: Circular Threat Index + Executive AI Summary */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Circular Threat Index Gauge */}
        <div className="lg:col-span-4">
          <ScoreGauge score={result.score} riskLevel={result.riskLevel} />
        </div>

        {/* Executive Summary & Category Breakdown */}
        <div className="lg:col-span-8 bg-slate-900/90 border border-slate-800 rounded-2xl p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <Cpu className="w-4 h-4 text-cyan-400" />
                <h3 className="text-sm font-mono uppercase tracking-wider font-semibold text-slate-200">
                  Forensic Safety Verdict
                </h3>
              </div>
              <span className="text-[11px] font-mono text-slate-400">
                {result.engine}
              </span>
            </div>

            <p className="text-slate-300 text-sm leading-relaxed mb-6 bg-slate-950/60 p-4 rounded-xl border border-slate-800/80">
              {result.summary}
            </p>

            {/* Risk Category Progress Bars */}
            <div className="space-y-3">
              <span className="text-xs font-mono uppercase tracking-wider text-slate-400 block mb-2">
                Threat Vector Sub-Scores:
              </span>

              <div className="space-y-2">
                <div>
                  <div className="flex justify-between text-xs font-mono mb-1">
                    <span className="text-slate-300">Advance Payment & Deposit Risk</span>
                    <span className="text-slate-400">{result.breakdown.paymentRisk}%</span>
                  </div>
                  <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all duration-700 ${
                        result.breakdown.paymentRisk > 50 ? "bg-rose-500" : "bg-emerald-500"
                      }`}
                      style={{ width: `${result.breakdown.paymentRisk}%` }}
                    />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs font-mono mb-1">
                    <span className="text-slate-300">Brand Impersonation & Identity Spoofing</span>
                    <span className="text-slate-400">{result.breakdown.identitySpoofing}%</span>
                  </div>
                  <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all duration-700 ${
                        result.breakdown.identitySpoofing > 50 ? "bg-orange-500" : "bg-cyan-500"
                      }`}
                      style={{ width: `${result.breakdown.identitySpoofing}%` }}
                    />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs font-mono mb-1">
                    <span className="text-slate-300">Coercive Urgency & Pressure Tactics</span>
                    <span className="text-slate-400">{result.breakdown.pressureUrgency}%</span>
                  </div>
                  <div className="w-full h-2 bg-slate-800 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all duration-700 ${
                        result.breakdown.pressureUrgency > 50 ? "bg-amber-500" : "bg-emerald-500"
                      }`}
                      style={{ width: `${result.breakdown.pressureUrgency}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
            <span>Scanned on: {new Date(result.timestamp).toLocaleTimeString()}</span>
            <span className="font-mono">SSRF & Rule Sandbox Active</span>
          </div>
        </div>
      </div>

      {/* Domain Forensics Card (If URL or Extracted Domain present) */}
      {result.domainIntelligence && (
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-4">
            <Globe className="w-4 h-4 text-cyan-400" />
            <h3 className="text-sm font-mono uppercase tracking-wider font-semibold text-slate-200">
              Domain & URL Forensic Intelligence
            </h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
            <div className="p-3 bg-slate-950/60 rounded-xl border border-slate-800">
              <span className="text-[11px] font-mono text-slate-400 block uppercase">Inspected Host</span>
              <span className="text-xs font-mono font-bold text-slate-200 truncate block mt-0.5">
                {result.domainIntelligence.domain}
              </span>
            </div>

            <div className="p-3 bg-slate-950/60 rounded-xl border border-slate-800">
              <span className="text-[11px] font-mono text-slate-400 block uppercase">Transport Protocol</span>
              <div className="flex items-center gap-1.5 mt-0.5">
                <Lock className={`w-3.5 h-3.5 ${result.domainIntelligence.isHttps ? "text-emerald-400" : "text-rose-400"}`} />
                <span className={`text-xs font-mono font-bold ${result.domainIntelligence.isHttps ? "text-emerald-400" : "text-rose-400"}`}>
                  {result.domainIntelligence.protocol.toUpperCase()}
                </span>
              </div>
            </div>

            <div className="p-3 bg-slate-950/60 rounded-xl border border-slate-800">
              <span className="text-[11px] font-mono text-slate-400 block uppercase">TLD Category</span>
              <span className={`text-xs font-mono font-bold block mt-0.5 ${result.domainIntelligence.isSuspiciousTld ? "text-rose-400" : "text-slate-200"}`}>
                .{result.domainIntelligence.tld} {result.domainIntelligence.isSuspiciousTld ? "(High Risk)" : "(Standard)"}
              </span>
            </div>

            <div className="p-3 bg-slate-950/60 rounded-xl border border-slate-800">
              <span className="text-[11px] font-mono text-slate-400 block uppercase">Brand Authenticity</span>
              <span className={`text-xs font-mono font-bold block mt-0.5 ${result.domainIntelligence.brandMismatch ? "text-rose-400" : "text-emerald-400"}`}>
                {result.domainIntelligence.brandMismatch ? "SPOOF DETECTED" : "Verified / Neutral"}
              </span>
            </div>
          </div>

          <div className="space-y-1.5">
            <span className="text-xs font-mono uppercase text-slate-400">Heuristic Analysis Notes:</span>
            <ul className="space-y-1 text-xs text-slate-300">
              {result.domainIntelligence.heuristicNotes.map((note, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <ChevronRight className="w-3.5 h-3.5 text-cyan-400 shrink-0 mt-0.5" />
                  <span>{note}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Red Flags & Evidence */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <AlertOctagon className="w-5 h-5 text-rose-400" />
            <h3 className="text-sm font-mono uppercase tracking-wider font-semibold text-slate-200">
              Detected Suspicious Indicators & Evidence ({result.redFlags.length})
            </h3>
          </div>
          {result.redFlags.length === 0 && (
            <span className="text-xs text-emerald-400 font-mono">Clean - Zero red flags</span>
          )}
        </div>

        {result.redFlags.length === 0 ? (
          <div className="p-5 bg-emerald-950/20 border border-emerald-800/40 rounded-xl text-center">
            <CheckCircle2 className="w-6 h-6 text-emerald-400 mx-auto mb-2" />
            <p className="text-sm text-emerald-300 font-medium">
              No overt fraud indicators or payment traps detected in the submitted input.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {result.redFlags.map((flag) => (
              <div
                key={flag.id}
                className="p-4 bg-slate-950/70 border border-slate-800/80 rounded-xl space-y-2 hover:border-slate-700 transition-colors"
              >
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-rose-500"></span>
                    <h4 className="text-sm font-semibold text-slate-100">{flag.title}</h4>
                  </div>
                  <span
                    className={`text-[10px] font-mono uppercase px-2 py-0.5 rounded border font-bold ${getSeverityBadge(
                      flag.severity
                    )}`}
                  >
                    {flag.severity}
                  </span>
                </div>

                {flag.evidence && (
                  <div className="p-2.5 bg-slate-900/90 rounded-lg border border-slate-800 text-xs text-rose-300 font-mono">
                    <span className="text-slate-400 select-none mr-1.5">&ldquo;</span>
                    {flag.evidence}
                    <span className="text-slate-400 select-none ml-1.5">&rdquo;</span>
                  </div>
                )}

                <p className="text-xs text-slate-400 leading-relaxed">
                  {flag.explanation}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Positive Signals Card */}
      {result.positiveSignals.length > 0 && (
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-4">
            <FileCheck className="w-4 h-4 text-emerald-400" />
            <h3 className="text-sm font-mono uppercase tracking-wider font-semibold text-slate-200">
              Positive Legitimate Trust Signals ({result.positiveSignals.length})
            </h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {result.positiveSignals.map((signal) => (
              <div
                key={signal.id}
                className="p-3.5 bg-slate-950/60 border border-slate-800 rounded-xl space-y-1"
              >
                <div className="flex items-center gap-2 text-xs font-semibold text-emerald-300">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                  <span>{signal.title}</span>
                </div>
                <p className="text-xs text-slate-400 pl-5 leading-relaxed">
                  {signal.explanation}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Actionable Safety Advice & Recommendations */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6">
        <div className="flex items-center gap-2 mb-4">
          <ShieldAlert className="w-4 h-4 text-cyan-400" />
          <h3 className="text-sm font-mono uppercase tracking-wider font-semibold text-slate-200">
            Actionable Safety Checklist & Next Steps
          </h3>
        </div>

        <ul className="space-y-2.5">
          {result.recommendations.map((rec, idx) => (
            <li
              key={idx}
              className="flex items-start gap-3 p-3 bg-slate-950/60 border border-slate-800/80 rounded-xl text-xs text-slate-300 leading-relaxed"
            >
              <div className="w-5 h-5 rounded-full bg-cyan-950 border border-cyan-800 flex items-center justify-center shrink-0 text-[10px] font-mono text-cyan-400 font-bold mt-0.5">
                {idx + 1}
              </div>
              <span>{rec}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};
